In [3]:
import pandas as pd

df = pd.read_csv('/customer_shopping_behavior.csv')

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/customer_shopping_behavior.csv'

In [ ]:
len(df)

5050

In [ ]:
df.shape

(5050, 17)

In [ ]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4494.000000,4449.000000,4502.000000
mean,2519.570891,44.150495,144.765236,3.668195,25.221901
std,1470.402964,15.282328,275.590101,0.865357,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

In [ ]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,5050.000000,5050.000000,5050,5050,5050,4494.000000,5050,4680,5050,5050,4449.000000,5050,5050,5050,4502.000000,5050,5050
unique,NaN,NaN,3,30,5,NaN,54,4,25,5,NaN,2,6,2,NaN,6,7
top,NaN,NaN,Male,Shirt,Clothing,NaN,New York,M,Black,Spring,NaN,No,Standard,No,NaN,Credit Card,Monthly
freq,NaN,NaN,3018,320,2130,NaN,337,1981,404,1280,NaN,3462,1213,2789,NaN,954,946
mean,2519.570891,44.150495,NaN,NaN,NaN,144.765236,NaN,NaN,NaN,NaN,3.668195,NaN,NaN,NaN,25.221901,NaN,NaN
std,1470.402964,15.282328,NaN,NaN,NaN,275.590101,NaN,NaN,NaN,NaN,0.865357,NaN,NaN,NaN,14.521635,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,10.120000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,0.000000,NaN,NaN
25%,1252.250000,31.000000,NaN,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,13.000000,NaN,NaN
50%,2499.500000,44.000000,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,25.000000,NaN,NaN
75%,3740.750000,57.000000,NaN,NaN,NaN,89.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,38.000000,NaN,NaN
max,5099.000000,70.000000,NaN,NaN,NaN,1499.760000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,50.000000,NaN,NaN

In [4]:
import pandas as pd

df = pd.read_csv('/content/customer_shopping_behavior.csv')

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [9]:
pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

In [34]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

## data cleaning

In [8]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [9]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [10]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [11]:
correct_mapping = {

    # Clothing
    "T-shirt": "Clothing",
    "Shirt": "Clothing",
    "Shorts": "Clothing",
    "Hoodie": "Clothing",
    "Pants": "Clothing",
    "Socks": "Clothing",
    "Jeans": "Clothing",
    "Blouse": "Clothing",
    "Skirt": "Clothing",
    "Sweater": "Clothing",
    "Dress": "Clothing",

    # Accessories
    "Sunglasses": "Accessories",
    "Gloves": "Accessories",
    "Jewelry": "Accessories",
    "Hat": "Accessories",
    "Handbag": "Accessories",
    "Backpack": "Accessories",
    "Belt": "Accessories",
    "Scarf": "Accessories",
    "Bag": "Accessories",

    # Electronics
    "Laptop": "Electronics",
    "Phone": "Electronics",
    "Headphones": "Electronics",
    "Watch": "Electronics",

    # Footwear
    "Shoes": "Footwear",
    "Sandals": "Footwear",
    "Sneakers": "Footwear",
    "Boots": "Footwear",

    # Outerwear
    "Coat": "Outerwear",
    "Jacket": "Outerwear"
}

In [12]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [13]:
df['category'] = df['Item Purchased'].map(correct_mapping)

In [14]:
df['category'] = df['Item Purchased'].map(correct_mapping)

In [15]:
df.groupby('category')['Item Purchased'].unique()

category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

In [16]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
category                    0
dtype: int64

## treating null values

size

In [17]:
df['Size'].unique()

array(['XL', 'M', 'L', 'S', nan], dtype=object)

In [18]:
df.groupby('Category')['Size'].unique()

Category
Accessories    [M, L, S, XL]
Clothing       [XL, M, S, L]
Electronics            [nan]
Footwear       [M, L, S, XL]
Outerwear      [XL, L, S, M]
Name: Size, dtype: object

In [19]:
df.groupby('Item Purchased')['Size'].unique()

Item Purchased
Backpack           [M, S, L, XL]
Bag           [M, L, nan, XL, S]
Belt               [M, S, XL, L]
Blouse             [M, L, S, XL]
Boots              [L, M, XL, S]
Coat               [XL, M, S, L]
Dress              [XL, M, L, S]
Gloves             [L, M, S, XL]
Handbag            [S, XL, M, L]
Hat                [M, L, S, XL]
Headphones    [S, M, nan, L, XL]
Hoodie             [M, L, S, XL]
Jacket             [L, S, M, XL]
Jeans              [L, M, XL, S]
Jewelry            [L, XL, M, S]
Laptop        [nan, M, S, XL, L]
Pants              [L, M, XL, S]
Phone         [nan, L, S, M, XL]
Sandals            [M, S, L, XL]
Scarf              [M, L, S, XL]
Shirt         [M, XL, L, S, nan]
Shoes         [M, L, nan, XL, S]
Shorts             [S, M, L, XL]
Skirt              [S, L, M, XL]
Sneakers           [S, M, L, XL]
Socks              [M, XL, L, S]
Sunglasses         [M, L, S, XL]
Sweater            [M, S, L, XL]
T-shirt            [XL, M, S, L]
Watch         [nan, M, L, XL, S]
Name: Size, dtype: object

In [20]:
df.loc[df['Category']=='Accessories','Size']="Free Size"

In [21]:
df.groupby('Category')['Size'].unique()

Category
Accessories      [Free Size]
Clothing       [XL, M, S, L]
Electronics            [nan]
Footwear       [M, L, S, XL]
Outerwear      [XL, L, S, M]
Name: Size, dtype: object

In [22]:
df.loc[df['Category']=='Electronics','Size']="not available"

In [23]:
df.groupby('Category')['Size'].unique()

Category
Accessories        [Free Size]
Clothing         [XL, M, S, L]
Electronics    [not available]
Footwear         [M, L, S, XL]
Outerwear        [XL, L, S, M]
Name: Size, dtype: object

In [24]:
df.loc[df['Category']=='Clothing','Size']="XL, M, S, L, nan"

In [25]:
df.groupby('Category')['Size'].unique()

Category
Accessories           [Free Size]
Clothing       [XL, M, S, L, nan]
Electronics       [not available]
Footwear            [M, L, S, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [26]:
df.loc[(df["Category"]=="Clothing") & (df["Size"].isnull()), "Size"] = df[df["Category"]=="Clothing"]["Size"].mode()[0]

In [27]:
df.groupby('Category')['Size'].unique()

Category
Accessories           [Free Size]
Clothing       [XL, M, S, L, nan]
Electronics       [not available]
Footwear            [M, L, S, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [28]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
category                    0
dtype: int64

## treating null value of review rating

In [29]:
# mean of review ratings
df['Review Rating'].mean()

np.float64(3.668195100022477)

In [31]:
# median of review ratings
df['Review Rating'].median()

3.7

In [32]:

# mode of review ratings
df['Review Rating'].mode()

0    4.0
Name: Review Rating, dtype: float64

In [33]:
df.groupby("Item Purchased")['Review Rating'].mean()

Item Purchased
Backpack      3.758333
Bag           3.168539
Belt          3.762963
Blouse        3.677647
Boots         3.813194
Coat          3.721875
Dress         3.750000
Gloves        3.862774
Handbag       3.771975
Hat           3.796753
Headphones    3.075949
Hoodie        3.716779
Jacket        3.761446
Jeans         3.651969
Jewelry       3.761850
Laptop        3.191176
Pants         3.720833
Phone         2.939024
Sandals       3.837037
Scarf         3.702564
Shirt         3.427273
Shoes         3.546154
Shorts        3.722981
Skirt         3.779747
Sneakers      3.757931
Socks         3.755063
Sunglasses    3.745679
Sweater       3.768712
T-shirt       3.790541
Watch         3.100000
Name: Review Rating, dtype: float64

In [34]:
#Filling null values of Review Ratings with the mean of each Item Purchased
df['Review Rating']=df['Review Rating'].fillna(df.groupby('Item Purchased')['Review Rating'] .transform ('mean'))

In [35]:
df.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases,category
0,2701,22,Female,T-shirt,Clothing,68.0,California,"XL, M, S, L, nan",Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly,Clothing
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly,Accessories
2,3157,18,Female,Shirt,Clothing,50.0,Montana,"XL, M, S, L, nan",Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly,Clothing
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually,Accessories
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly,Accessories

In [36]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
category                    0
dtype: int64

## previous purchase

In [37]:

# Filling Previous Purchases with Zero(0)
df['Previous Purchases']=df['Previous Purchases'].fillna(0)

In [38]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
category                    0
dtype: int64

## purchase amount

In [39]:
df.groupby("Item Purchased")['Purchase Amount (USD)'].mean()

Item Purchased
Backpack       60.111111
Bag           735.773625
Belt           59.993902
Blouse         60.802326
Boots          62.616438
Coat           57.851852
Dress          62.168675
Gloves         60.550000
Handbag        57.987261
Hat            60.787097
Headphones    831.344565
Hoodie         58.059603
Jacket         56.777108
Jeans          60.456693
Jewelry        59.011494
Laptop        805.502027
Pants          59.005848
Phone         734.477349
Sandals        57.527607
Scarf          61.157233
Shirt         279.935608
Shoes         276.343790
Shorts         60.073620
Skirt          59.723270
Sneakers       59.551724
Socks          58.188679
Sunglasses     59.975610
Sweater        57.638554
T-shirt        63.093333
Watch         685.231471
Name: Purchase Amount (USD), dtype: float64

In [40]:
#Filling null values of Purchase Amount (USD) with the mean of each Item Purchased
df['Purchase Amount (USD)']=df['Purchase Amount (USD)'].fillna(df.groupby('Item Purchased')['Purchase Amount (USD)'] .transform ('mean'))

In [41]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
category                  0
dtype: int64

### checking duplicate value

In [42]:
df.duplicated().sum()

np.int64(50)

In [43]:
df[df.duplicated()]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases,category
886,2834,43,Female,Jeans,Clothing,56.0,Arkansas,"XL, M, S, L, nan",Teal,Fall,3.300000,No,Free Shipping,No,19.0,Cash,Monthly,Clothing
1402,1621,25,Male,Hat,Accessories,47.0,Virginia,Free Size,Charcoal,Winter,3.100000,No,2-Day Shipping,Yes,27.0,PayPal,Every 3 Months,Accessories
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.500000,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly,Outerwear
1600,2135,55,Male,Sandals,Footwear,41.0,Virginia,XL,Maroon,Winter,2.900000,No,Standard,No,35.0,Credit Card,Fortnightly,Footwear
1665,1846,51,Male,Sandals,Footwear,78.0,Delaware,M,Orange,Winter,2.800000,No,2-Day Shipping,No,39.0,Bank Transfer,Quarterly,Footwear
1797,3639,40,Female,Backpack,Accessories,20.0,Kansas,Free Size,Olive,Spring,4.600000,No,Express,No,50.0,PayPal,Bi-Weekly,Accessories
1870,3456,49,Female,T-shirt,Clothing,89.0,Ohio,"XL, M, S, L, nan",Orange,Fall,4.700000,No,Standard,No,13.0,Venmo,Annually,Clothing
2033,1812,42,Male,Belt,Accessories,77.0,Wisconsin,Free Size,Blue,Summer,3.600000,No,Standard,No,33.0,Bank Transfer,Annually,Accessories
2113,3040,59,Female,Blouse,Clothing,48.0,Alabama,"XL, M, S, L, nan",Blue,Spring,3.200000,No,Next Day Air,No,31.0,PayPal,Bi-Weekly,Clothing
2226,1371,27,Male,Scarf,Accessories,67.0,Montana,Free Size,Peach,Summer,3.702564,No,2-Day Shipping,Yes,41.0,Bank Transfer,Every 3 Months,Accessories
2358,2977,30,Female,Coat,Outerwear,97.0,Nebraska,M,Silver,Summer,2.800000,No,Express,No,28.0,Cash,Fortnightly,Outerwear
2447,2678,45,Female,Shorts,Clothing,43.0,Connecticut,"XL, M, S, L, nan",Olive,Spring,3.800000,No,Next Day Air,No,6.0,PayPal,Every 3 Months,Clothing
2630,992,20,Male,Shorts,Clothing,97.0,Wisconsin,"XL, M, S, L, nan",White,Spring,2.700000,Yes,Standard,Yes,40.0,Bank Transfer,Bi-Weekly,Clothing
2642,1566,58,Male,Sunglasses,Accessories,93.0,Idaho,Free Size,Peach,Fall,4.200000,No,Free Shipping,Yes,48.0,PayPal,Annually,Accessories
2739,2227,22,Male,Shirt,Clothing,72.0,Missouri,"XL, M, S, L, nan",Blue,Spring,4.800000,No,Store Pickup,No,28.0,Cash,Annually,Clothing
2740,3487,51,Female,Shorts,Clothing,89.0,North Carolina,"XL, M, S, L, nan",Charcoal,Winter,4.900000,No,Standard,No,6.0,PayPal,Weekly,Clothing
2800,2069,70,Male,Jewelry,Accessories,81.0,Vermont,Free Size,Black,Summer,3.900000,No,Store Pickup,No,44.0,Venmo,Monthly,Accessories
2905,2158,41,Male,Handbag,Accessories,68.0,Mississippi,Free Size,Turquoise,Winter,4.000000,No,Next Day Air,No,41.0,Venmo,Fortnightly,Accessories
2922,3334,55,Female,Jeans,Clothing,35.0,Minnesota,"XL, M, S, L, nan",Violet,Spring,4.200000,No,Express,No,3.0,PayPal,Monthly,Clothing
3036,258,20,Male,Handbag,Accessories,53.0,West Virginia,Free Size,Red,Summer,4.500000,Yes,Express,Yes,5.0,Credit Card,Quarterly,Accessories
3065,3887,37,Female,Jewelry,Accessories,92.0,Iowa,Free Size,Brown,Summer,3.900000,No,Express,No,40.0,Debit Card,Quarterly,Accessories
3185,1609,26,Male,Sandals,Footwear,58.0,Nebraska,XL,Cyan,Fall,4.600000,No,Next Day Air,Yes,12.0,Bank Transfer,Bi-Weekly,Footwear
3357,3091,29,Female,Shirt,Clothing,36.0,Texas,"XL, M, S, L, nan",Peach,Summer,4.900000,No,Store Pickup,No,15.0,Bank Transfer,Quarterly,Clothing
3390,603,37,Male,Shoes,Footwear,58.0,Oregon,L,Lavender,Summer,4.200000,Yes,Next Day Air,Yes,10.0,Cash,Every 3 Months,Footwear
3538,1698,36,Male,Shirt,Clothing,87.0,South Carolina,"XL, M, S, L, nan",Lavender,Fall,3.500000,No,Next Day Air,No,48.0,Credit Card,Every 3 Months,Clothing
3683,1209,20,Male,Boots,Footwear,100.0,Wisconsin,S,Red,Winter,3.813194,No,2-Day Shipping,Yes,8.0,Debit Card,Annually,Footwear
3698,172,29,Male,Shorts,Clothing,35.0,Virginia,"XL, M, S, L, nan",Blue,Summer,3.600000,Yes,Store Pickup,Yes,4.0,Credit Card,Weekly,Clothing
3742,323,41,Male,Belt,Accessories,95.0,Tennessee,Free Size,Cyan,Winter,3.000000,Yes,Standard,Yes,47.0,Credit Card,Monthly,Accessories
3810,2429,65,Male,T-shirt,Clothing,38.0,Idaho,"XL, M, S, L, nan",Violet,Spring,4.400000,No,Next Day Air,No,34.0,Debit Card,Annually,Clothing
3843,615,68,Male,Jewelry,Accessories,85.0,Idaho,Free Size,Lavender,Winter,4.000000,Yes,Standard,Yes,21.0,Credit Card,Bi-Weekly,Accessories
3961,2558,70,Male,Shorts,Clothing,23.0,Oklahoma,"XL, M, S, L, nan",Cyan,Spring,3.900000,No,Standard,No,17.0,PayPal,Fortnightly,Clothing
3987,3507,18,Female,Shirt,Clothing,57.0,Illinois,"XL, M, S, L, nan",Olive,Winter,3.700000,No,2-Day Shipping,No,12.0,Cash,Fortnightly,Clothing
4050,3287,45,Female,Jacket,Outerwear,67.0,Illinois,L,Pink,Winter,5.000000,No,Express,No,4.0,Venmo,Fortnightly,Outerwear
4059,227,29,Male,Shoes,Footwear,74.0,Texas,L,Violet,Spring,3.300000,Yes,Free Shipping,Yes,5.0,PayPal,Monthly,Footwear
4131,2642,25,Male,Sunglasses,Accessories,60.0,Vermont,Free Size,Olive,Winter,2.700000,No,Next Day Air,No,20.0,Bank Transfer,Every 3 Months,Accessories
4183,1523,38,Male,Shorts,Clothing,72.0,Tennessee,"XL, M, S, L, nan",Yellow,Spring,4.800000,No,Free Shipping,Yes,5.0,Debit Card,Monthly,Clothing
4330,3716,63,Female,Sunglasses,Accessories,34.0,Nebraska,Free Size,Orange,Fall,3.400000,No,Free Shipping,No,2.0,Bank Transfer,Monthly,Accessories
4390,3846,58,Female,Sweater,Clothing,52.0,California,"XL, M, S, L, nan",Green,Winter,4.900000,No,Standard,No,46.0,Venmo,Annually,Clothing
4445,3644,53,Female,Scarf,Accessories,96.0,Tennessee,Free Size,Magenta,Fall,3.200000,No,Standard,No,47.0,Debit Card,Annually,Accessories
4468,473,20,Male,Jeans,Clothing,39.0,Georgia,"XL, M, S, L, nan",Gray,Winter,3.900000,Yes,Free Shipping,Yes,3.0,Bank Transfer,Quarterly,Clothing
4513,1317,28,Male,Belt,Accessories,32.0,Arkansas,Free Size,Lavender,Spring,4.600000,No,Standard,Yes,14.0,Debit Card,Bi-Weekly,Accessories
4558,3339,29,Female,Skirt,Clothing,94.0,Minnesota,"XL, M, S, L, nan",White,Winter,2.900000,No,2-Day Shipping,No,46.0,Credit Card,Monthly,Clothing
4595,3577,29,Female,Boots,Footwear,24.0,Maine,L,Yellow,Spring,3.000000,No,Express,No,12.0,Venmo,Bi-Weekly,Footwear
4664,2689,53,Female,Handbag,Accessories,63.0,West Virginia,Free Size,Turquoise,Spring,2.900000,No,2-Day Shipping,No,18.0,Credit Card,Every 3 Months,Accessories
4717,2800,23,Female,T-shirt,Clothing,89.0,Maine,"XL, M, S, L, nan",Pink,Spring,3.900000,No,Free Shipping,No,9.0,Bank Transfer,Every 3 Months,Clothing
4735,2182,22,Male,Handbag,Accessories,63.0,Hawaii,Free Size,Black,Fall,3.200000,No,Free Shipping,No,32.0,Bank Transfer,Bi-Weekly,Accessories
4841,2622,48,Male,Shoes,Footwear,46.0,Maine,M,Beige,Winter,3.000000,No,Express,No,21.0,Bank Transfer,Annually,Footwear
4887,3875,70,Female,Sweater,Clothing,54.0,Nevada,"XL, M, S, L, nan",Beige,Summer,3.900000,No,2-Day Shipping,No,33.0,Credit Card,Bi-Weekly,Clothing
4901,1060,22,Male,Jacket,Outerwear,34.0,North Carolina,M,Beige,Winter,2.500000,No,Standard,Yes,25.0,Debit Card,Monthly,Outerwear
5037,3439,26,Female,Shirt,Clothing,71.0,Kentucky,"XL, M, S, L, nan",Violet,Fall,3.000000,No,Store Pickup,No,33.0,Credit Card,Monthly,Clothing

In [44]:
df[df['Customer ID']==227]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases,category
1569,227,29,Male,Shoes,Footwear,74.0,Texas,L,Violet,Spring,3.3,Yes,Free Shipping,Yes,5.0,PayPal,Monthly,Footwear
4059,227,29,Male,Shoes,Footwear,74.0,Texas,L,Violet,Spring,3.3,Yes,Free Shipping,Yes,5.0,PayPal,Monthly,Footwear

In [47]:
# Deleting duplicate records
df=df.drop_duplicates(subset=['Customer ID'],keep='first')

In [48]:
len(df)

5000

## renamin the headers

In [87]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases', 'category'],
      dtype='object')

In [49]:
df.columns=df.columns.str.replace(" ","_")
df.columns=df.columns.str.lower()

In [50]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'category'],
      dtype='object')

In [51]:
#replacing purchase_amount_(usd) to purchase_amount
df=df.rename(columns={"purchase_amount_(usd)":"purchase_amount"})

In [52]:

df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'category'],
      dtype='object')

In [53]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,category
0,2701,22,Female,T-shirt,Clothing,68.0,California,"XL, M, S, L, nan",Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly,Clothing
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly,Accessories
2,3157,18,Female,Shirt,Clothing,50.0,Montana,"XL, M, S, L, nan",Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly,Clothing
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually,Accessories
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly,Accessories

In [93]:
!pip install pyodbc sqlalchemy

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading pyodbc-5.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (340 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 340.3/340.3 kB 6.2 MB/s eta 0:00:00
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0

In [1]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp312-cp312-manylinux_2_28_x86_64.whl (21.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.7/21.7 MB 28.7 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

In [55]:
df.to_csv('cleaned_data.csv', index=False)

In [56]:
from google.colab import files

files.download('cleaned_data.csv')

In [57]:
len(df)

5000

In [58]:
import csv

df.to_csv(
    'cleaned_data.csv',
    index=False,
    encoding='utf-8',
    quoting=csv.QUOTE_ALL
)

In [59]:
from google.colab import files

files.download('cleaned_data.csv')